# Generated by Django 2.2.5 on 2019-09-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='_file',
            new_name='f',
        ),
    ]
